# Generated by Django 4.2.6 on 2023-11-08 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=100, verbose_name='計畫名稱')),
                ('estimated_start_date', models.DateField(null=True, verbose_name='預計開始時間')),
                ('estimated_completion_date', models.DateField(null=True, verbose_name='預計結束時間')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最後更新時間')),
            ],
            options={
                'db_table': 'plan',
                'ordering': ('id',),
            },
        ),
    ]
