# Generated by Django 4.2.6 on 2024-03-14 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogisticParameters',
            fields=[
                ('parameter_id', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('midpoint_time', models.DecimalField(decimal_places=2, max_digits=10)),
                ('growth_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'logistic_parameters',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LogisticParametersHistory',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('changed_column', models.CharField(max_length=255)),
                ('previous_value', models.TextField()),
                ('new_value', models.TextField()),
                ('change_type', models.CharField(max_length=50)),
                ('change_time', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.CharField(max_length=255)),
                ('change_reason', models.TextField()),
                ('change_description', models.TextField()),
            ],
            options={
                'db_table': 'logistic_parameters_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MajorItemPercentage',
            fields=[
                ('major_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=255)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'major_item_percentage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MajorItemPercentageHistory',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('changed_column', models.CharField(max_length=255)),
                ('previous_value', models.TextField()),
                ('new_value', models.TextField()),
                ('change_type', models.CharField(max_length=50)),
                ('change_time', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.CharField(max_length=255)),
                ('change_reason', models.TextField()),
                ('change_description', models.TextField()),
            ],
            options={
                'db_table': 'major_item_percentage_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectPV',
            fields=[
                ('pv_id', models.AutoField(primary_key=True, serialize=False)),
                ('pv_name', models.CharField(max_length=255)),
                ('planned_start_date', models.DateField()),
                ('planned_end_date', models.DateField()),
                ('actual_start_date', models.DateField(blank=True, null=True)),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('construction_status', models.CharField(max_length=255)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'project_pv',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectPVExpectedProgress',
            fields=[
                ('expected_progress_id', models.AutoField(primary_key=True, serialize=False)),
                ('progress_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('calculation_date', models.DateField()),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pv_expected_progress',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectPVHistory',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('changed_column', models.CharField(max_length=255)),
                ('previous_value', models.TextField()),
                ('new_value', models.TextField()),
                ('change_type', models.CharField(max_length=50)),
                ('change_time', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.CharField(max_length=255)),
                ('change_reason', models.TextField()),
                ('change_description', models.TextField()),
            ],
            options={
                'db_table': 'project_pv_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectPVProgress',
            fields=[
                ('progress_id', models.AutoField(primary_key=True, serialize=False)),
                ('progress_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('supervisor', models.CharField(max_length=255)),
                ('non_construction_reason', models.TextField()),
                ('progress_calculation_description', models.TextField()),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pv_progress',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PVBankExpectedHistory',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('changed_column', models.CharField(max_length=255)),
                ('previous_value', models.TextField()),
                ('new_value', models.TextField()),
                ('change_type', models.CharField(max_length=50)),
                ('change_time', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.CharField(max_length=255)),
                ('change_reason', models.TextField()),
                ('change_description', models.TextField()),
            ],
            options={
                'db_table': 'pv_bank_expected_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PVBankHistory',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('changed_column', models.CharField(max_length=255)),
                ('previous_value', models.TextField()),
                ('new_value', models.TextField()),
                ('change_type', models.CharField(max_length=50)),
                ('change_time', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.CharField(max_length=255)),
                ('change_reason', models.TextField()),
                ('change_description', models.TextField()),
            ],
            options={
                'db_table': 'pv_bank_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PVBankProgress',
            fields=[
                ('pv_bank_id', models.AutoField(primary_key=True, serialize=False)),
                ('progress_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pvbank_progress',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PVBankProgressExpected',
            fields=[
                ('pv_bank_expected_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_parameter_based', models.BooleanField(default=True)),
                ('progress_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pvbank_progress_expected',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PvWeek',
            fields=[
                ('week_id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('quarter', models.IntegerField(blank=True, null=True)),
                ('week', models.IntegerField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pv_week',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('series_id', models.AutoField(primary_key=True, serialize=False)),
                ('series_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'series',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SeriesHistory',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('changed_column', models.CharField(max_length=255)),
                ('previous_value', models.TextField()),
                ('new_value', models.TextField()),
                ('change_type', models.CharField(max_length=50)),
                ('change_time', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.CharField(max_length=255)),
                ('change_reason', models.TextField()),
                ('change_description', models.TextField()),
            ],
            options={
                'db_table': 'series_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubItemPercentage',
            fields=[
                ('sub_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=255)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sub_item_percentage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubItemPercentageHistory',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('changed_column', models.CharField(max_length=255)),
                ('previous_value', models.TextField()),
                ('new_value', models.TextField()),
                ('change_type', models.CharField(max_length=50)),
                ('change_time', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.CharField(max_length=255)),
                ('change_reason', models.TextField()),
                ('change_description', models.TextField()),
            ],
            options={
                'db_table': 'sub_item_percentage_history',
                'managed': False,
            },
        ),
    ]
