# Generated by Django 4.2.6 on 2024-03-13 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyProductionRatio',
            fields=[
                ('ratio_id', models.AutoField(primary_key=True, serialize=False)),
                ('ratio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('effective_date', models.DateField()),
                ('created_by', models.CharField(max_length=255)),
                ('updated_by', models.CharField(max_length=255)),
                ('last_update', models.DateField()),
                ('create_at', models.DateField()),
            ],
            options={
                'db_table': 'energy_production_ratio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EnergyProductionSeries',
            fields=[
                ('series_id', models.AutoField(primary_key=True, serialize=False)),
                ('series_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_by', models.CharField(max_length=255)),
                ('updated_by', models.CharField(max_length=255)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'energy_production_series',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FileProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_link', models.CharField(max_length=255)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_description', models.TextField(blank=True, null=True)),
                ('routeName', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'file_progress',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MasterPlan',
            fields=[
                ('master_plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('master_plan_name', models.CharField(max_length=255)),
                ('planned_start_date', models.DateField()),
                ('planned_end_date', models.DateField()),
                ('actual_start_date', models.DateField(blank=True, null=True)),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('master_plan_manager', models.CharField(max_length=255)),
                ('master_plan_status', models.CharField(max_length=255)),
                ('master_plan_description', models.TextField()),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'master_plans',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MasterPlanProgress',
            fields=[
                ('progress_id', models.AutoField(primary_key=True, serialize=False)),
                ('progress_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('progress_description', models.TextField()),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'master_plan_progress',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MasterPlansHistory',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('changed_column', models.CharField(max_length=255)),
                ('previous_value', models.TextField()),
                ('new_value', models.TextField()),
                ('change_type', models.CharField(max_length=50)),
                ('change_time', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.CharField(max_length=255)),
                ('change_reason', models.TextField()),
                ('change_description', models.TextField()),
            ],
            options={
                'db_table': 'master_plans_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MeetingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_link', models.CharField(max_length=255)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_description', models.TextField(blank=True, null=True)),
                ('routeName', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'meeting_record',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('plan_name', models.CharField(max_length=255)),
                ('planned_start_date', models.DateField(blank=True, null=True)),
                ('planned_end_date', models.DateField(blank=True, null=True)),
                ('actual_start_date', models.DateField(blank=True, null=True)),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('plan_manager', models.CharField(blank=True, max_length=255, null=True)),
                ('plan_status', models.CharField(blank=True, max_length=255, null=True)),
                ('plan_description', models.TextField(blank=True, null=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'plans',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlanAssociation',
            fields=[
                ('association_id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_date', models.DateField()),
                ('notes', models.TextField()),
            ],
            options={
                'db_table': 'plan_associations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlansHistory',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('changed_column', models.CharField(max_length=255)),
                ('previous_value', models.TextField()),
                ('new_value', models.TextField()),
                ('change_type', models.CharField(max_length=50)),
                ('change_time', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.CharField(max_length=255)),
                ('change_reason', models.TextField()),
                ('change_description', models.TextField()),
            ],
            options={
                'db_table': 'plans_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlansProgress',
            fields=[
                ('progress_id', models.AutoField(primary_key=True, serialize=False)),
                ('progress_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('progress_description', models.TextField()),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'plans_progress',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlanTotalEnergyProduction',
            fields=[
                ('plan_total_energy_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_energy_production', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=50)),
                ('effective_date', models.DateField()),
                ('created_by', models.CharField(max_length=255)),
                ('updated_by', models.CharField(max_length=255)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'plan_total_energy_production',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlanWeight',
            fields=[
                ('weight_id', models.AutoField(primary_key=True, serialize=False)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('effective_date', models.DateField()),
                ('adjustment_reason', models.TextField()),
            ],
            options={
                'db_table': 'plan_weights',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectCaseEnergyProduction',
            fields=[
                ('case_energy_id', models.AutoField(primary_key=True, serialize=False)),
                ('energy_production', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=50)),
                ('effective_date', models.DateField()),
                ('created_by', models.CharField(max_length=255)),
                ('updated_by', models.CharField(max_length=255)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'project_case_energy_production',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectLoopEnergyProduction',
            fields=[
                ('loop_energy_id', models.AutoField(primary_key=True, serialize=False)),
                ('energy_production', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=50)),
                ('effective_date', models.DateField()),
                ('created_by', models.CharField(max_length=255)),
                ('updated_by', models.CharField(max_length=255)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'project_loop_energy_production',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectValueRatio',
            fields=[
                ('ratio_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_id', models.IntegerField()),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.TextField()),
                ('effective_date', models.DateField()),
                ('created_by', models.CharField(max_length=255)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('last_update', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'project_value_ratios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectValueRatiosHistory',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('changed_column', models.CharField(max_length=255)),
                ('previous_value', models.TextField()),
                ('new_value', models.TextField()),
                ('change_type', models.CharField(max_length=50)),
                ('change_time', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.CharField(max_length=255)),
                ('change_reason', models.TextField()),
                ('change_description', models.TextField()),
            ],
            options={
                'db_table': 'project_value_ratios_history',
                'managed': False,
            },
        ),
    ]
