# Generated by Django 4.2.6 on 2024-03-20 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BreedingBankExpectedHistory',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('changed_column', models.CharField(max_length=255)),
                ('previous_value', models.TextField()),
                ('new_value', models.TextField()),
                ('change_type', models.CharField(max_length=50)),
                ('change_time', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.CharField(max_length=255)),
                ('change_reason', models.TextField()),
                ('change_description', models.TextField()),
            ],
            options={
                'db_table': 'breeding_bank_expected_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BreedingBankHistory',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('changed_column', models.CharField(max_length=255)),
                ('previous_value', models.TextField()),
                ('new_value', models.TextField()),
                ('change_type', models.CharField(max_length=50)),
                ('change_time', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.CharField(max_length=255)),
                ('change_reason', models.TextField()),
                ('change_description', models.TextField()),
            ],
            options={
                'db_table': 'breeding_bank_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BreedingBankProgress',
            fields=[
                ('breeding_bank_id', models.AutoField(primary_key=True, serialize=False)),
                ('progress_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'breedingbank_progress',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BreedingBankProgressExpected',
            fields=[
                ('breeding_bank_expected_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_parameter_based', models.BooleanField(default=True)),
                ('progress_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'breedingbank_progress_expected',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BreedingWeek',
            fields=[
                ('week_id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('quarter', models.IntegerField(blank=True, null=True)),
                ('week', models.IntegerField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'breeding_week',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectBreeding',
            fields=[
                ('breeding_id', models.AutoField(primary_key=True, serialize=False)),
                ('breeding_name', models.CharField(max_length=255)),
                ('planned_start_date', models.DateField()),
                ('planned_end_date', models.DateField()),
                ('actual_start_date', models.DateField(blank=True, null=True)),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('construction_status', models.CharField(max_length=255)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'project_breeding',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectBreedingExpectedProgress',
            fields=[
                ('expected_progress_id', models.AutoField(primary_key=True, serialize=False)),
                ('progress_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('calculation_date', models.DateField()),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'breeding_expected_progress',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectBreedingHistory',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('changed_column', models.CharField(max_length=255)),
                ('previous_value', models.TextField()),
                ('new_value', models.TextField()),
                ('change_type', models.CharField(max_length=50)),
                ('change_time', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.CharField(max_length=255)),
                ('change_reason', models.TextField()),
                ('change_description', models.TextField()),
            ],
            options={
                'db_table': 'project_breeding_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectBreedingProgress',
            fields=[
                ('progress_id', models.AutoField(primary_key=True, serialize=False)),
                ('progress_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('supervisor', models.CharField(max_length=255)),
                ('non_construction_reason', models.TextField()),
                ('progress_calculation_description', models.TextField()),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'breeding_progress',
                'managed': False,
            },
        ),
    ]
