# Generated by Django 4.2.6 on 2023-11-24 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalProjectExpectedProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loop_name', models.CharField(blank=True, max_length=255, null=True)),
                ('historical_case', models.CharField(blank=True, max_length=255, null=True)),
                ('estimated_start_date', models.DateField(blank=True, null=True)),
                ('estimated_completion_date', models.DateField(blank=True, null=True)),
                ('historical_progress_rate', models.FloatField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'historical_pv_expected',
                'ordering': ('id',),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalProjectProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loop_name', models.CharField(blank=True, max_length=255, null=True)),
                ('historical_case', models.CharField(blank=True, max_length=255, null=True)),
                ('estimated_start_date', models.DateField(blank=True, null=True)),
                ('estimated_completion_date', models.DateField(blank=True, null=True)),
                ('historical_progress_rate', models.FloatField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'historical_pv_records',
                'ordering': ('id',),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SeasonHistoricalProjectExpectedProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('historical_loop', models.CharField(blank=True, max_length=255, null=True)),
                ('estimated_start_date', models.DateField(blank=True, null=True)),
                ('estimated_completion_date', models.DateField(blank=True, null=True)),
                ('historical_progress_rate', models.FloatField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'historical_pv_expected_season',
                'ordering': ('id',),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SeasonHistoricalProjectProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('historical_loop', models.CharField(blank=True, max_length=255, null=True)),
                ('estimated_start_date', models.DateField(blank=True, null=True)),
                ('estimated_completion_date', models.DateField(blank=True, null=True)),
                ('historical_progress_rate', models.FloatField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'historical_pv_records_season',
                'ordering': ('id',),
                'managed': False,
            },
        ),
    ]
