# Generated by Django 4.2.6 on 2023-12-15 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pv_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PvBank',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('progress', models.FloatField(blank=True, null=True)),
                ('personnel', models.CharField(blank=True, max_length=50, null=True)),
                ('cause', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pv_bank',
                'ordering': ('id',),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PvExpected',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('progress', models.FloatField(blank=True, null=True)),
                ('personnel', models.CharField(blank=True, max_length=50, null=True)),
                ('cause', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pv_expected',
                'ordering': ('id',),
                'managed': False,
            },
        ),
    ]
