# Generated by Django 4.2.6 on 2023-10-24 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PV_DetailedItemWeightModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detailed_name', models.CharField(max_length=255, verbose_name='細項工程')),
                ('detailed_weight', models.FloatField(null=True, verbose_name='細項權重')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最後更新時間')),
            ],
            options={
                'db_table': 'pv_detaileditem_weight',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='PV_TaskModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最後更新時間')),
            ],
            options={
                'db_table': 'pv_tasks',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='PV_SubItemWeightModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subitem_name', models.CharField(max_length=255, verbose_name='分項工程')),
                ('subitem_weight', models.FloatField(null=True, verbose_name='分向權重')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最後更新時間')),
                ('tasks_id', models.ForeignKey(db_column='tasks_id', on_delete=django.db.models.deletion.CASCADE, related_name='sub_items', to='project_app_pv.pv_taskmodel')),
            ],
            options={
                'db_table': 'pv_subitem_weight',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='PV_ProjectModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_code', models.CharField(max_length=255, verbose_name='工程代號')),
                ('project_name', models.CharField(max_length=255, verbose_name='工程名稱')),
                ('project_location', models.CharField(max_length=255, verbose_name='工程地點')),
                ('project_area', models.CharField(max_length=255, verbose_name='工程區域')),
                ('project_status', models.IntegerField(choices=[(0, '未開工'), (1, '完工'), (2, '施工中'), (3, '停工')], default=0, verbose_name='工程狀態')),
                ('estimated_start_date', models.DateField(null=True, verbose_name='預計開始時間')),
                ('estimated_completion_date', models.DateField(null=True, verbose_name='預計結束時間')),
                ('actual_start_date', models.DateField(null=True, verbose_name='實際開始時間')),
                ('actual_completion_date', models.DateField(null=True, verbose_name='實際結束時間')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最後更新時間')),
                ('tasks_id', models.ForeignKey(db_column='tasks_id', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='project_app_pv.pv_taskmodel')),
            ],
            options={
                'db_table': 'pv_project',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='PV_ProgressModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(null=True, verbose_name='開始日期')),
                ('completion_date', models.DateField(null=True, verbose_name='結束日期')),
                ('progress', models.FloatField(null=True, verbose_name='進度')),
                ('personnel', models.CharField(max_length=50, null=True, verbose_name='現場監工')),
                ('cause', models.TextField(null=True, verbose_name='未施工原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最後更新時間')),
                ('expected_id', models.ForeignKey(db_column='expected_id', on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='project_app_pv.pv_projectmodel')),
            ],
            options={
                'db_table': 'pv_progress',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='PV_ExpectedProgressModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_start_date', models.DateField(null=True, verbose_name='預計開始時間')),
                ('estimated_completion_date', models.DateField(null=True, verbose_name='預計結束時間')),
                ('actual_start_date', models.DateField(null=True, verbose_name='實際開始時間')),
                ('actual_completion_date', models.DateField(null=True, verbose_name='實際結束時間')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最後更新時間')),
                ('detailed_id', models.ForeignKey(db_column='detailed_id', on_delete=django.db.models.deletion.CASCADE, related_name='expected_progress', to='project_app_pv.pv_detaileditemweightmodel')),
                ('project_id', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, related_name='expected_progress', to='project_app_pv.pv_projectmodel')),
                ('subitem_id', models.ForeignKey(db_column='subitem_id', on_delete=django.db.models.deletion.CASCADE, related_name='expected_progress', to='project_app_pv.pv_subitemweightmodel')),
            ],
            options={
                'db_table': 'pv_expected_progress',
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='pv_detaileditemweightmodel',
            name='subitem_id',
            field=models.ForeignKey(db_column='subitem_id', on_delete=django.db.models.deletion.CASCADE, related_name='detailed_items', to='project_app_pv.pv_taskmodel'),
        ),
    ]
